name: Visit Website

on:
  workflow_dispatch:

jobs:
  visit-website:
    runs-on: windows-latest
    steps:
      - name: Install Chrome
        run: |
          choco install googlechrome
      - name: Set user agent
        run: |
          $chromeUA = (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/nelsonic/user-agents/master/browsers/chrome.txt')
          $chromeUA = $chromeUA.Split("`n")[0]
          $env:USER_AGENT = $chromeUA
      - name: Visit website
        run: |
          for ($i = 1; $i -le 99; $i++) { Invoke-WebRequest -Uri "https://www.toprevenuegate.com/encqvawkv7?key=7d519a06f91319101fad175a4c4c7e8e" -UserAgent $env:USER_AGENT }
