name: Visit Website

on:
  workflow_dispatch:

jobs:
  visit-website:
    runs-on: ubuntu-latest
    steps:
      - name: Set user agent
        run: |
          export USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
      - name: Visit website
        run: |
          for i in $(seq 1 99); do curl -s -A "$USER_AGENT" https://www.toprevenuegate.com/encqvawkv7?key=7d519a06f91319101fad175a4c4c7e8e; done
